name: ci

on:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  build_test_release:
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v2
      - name: Run always
        run: echo "Hello GH Actions"

