name: ci

on:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  matrix_builder:
    runs-on: ubuntu-latest
    outputs:
      node-version-matrix: ${{ steps.set-node-matrix.outputs.node-version-matrix }}
      os-matrix: ${{ steps.set-os-matrix.outputs.os-matrix }}
    steps:
      - id: set-node-matrix
        run: if $GITHUB_REF === 'main'; then echo "::set-output name=node-version-matrix::[16]"; else echo "::set-output name=node-version-matrix::[12, 14, 16]"; fi
      - id: set-os-matrix
        run: if $GITHUB_REF === 'main'; then echo "::set-output name=os-matrix::['ubuntu-latest']"; else echo  "::set-output name=os-matrix::['ubuntu-latest', 'windows-latest']"; fi

  build_test_release:
    needs: matrix_builder
    strategy:
      matrix:
        node-version: fromJSON(needs.matrix_builder.outputs.node-version-matrix)
        os: fromJSON(needs.matrix_builder.outputs.os-matrix)
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run always
        run: echo "Hello GH Actions"
      - name: Run on merge to main
        if: github.repository == 'timdeschryver/gh-actions-sandbox' && github.ref == 'refs/heads/main'
        run: echo "Hello main"
